//notification types
export const  NotificationActionType = {
	MESSAGE_OBJ :"MESSAGE_OBJ"
};

// auth types
export const AuthActionType = {
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	LOGIN_FAILED:"LOGIN_FAILED",
	LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
	LOGOUT_FAILED:'LOGOUT_FAILED',
	SET_USER_PERMISSION:'SET_USER_PERMISSION',
}

//log types
export const LogActionType ={
	SET_LOG:'SET_LOG'
}

//message types
export const ChatActionType={
	CHAT_USER_LIST_SUCCESS:"CHAT_USER_LIST_SUCCESS",
	CHAT_USER_ACTIVE_LIST_SUCCESS:"CHAT_USER_ACTIVE_LIST_SUCCESS",
	CHAT_USER_MESSAGE_LIST_SUCCESS : "CHAT_USER_MESSAGE_LIST_SUCCESS",
	CHAT_MESSAGE_CREATED_SUCCESS:"CHAT_MESSAGE_CREATED_SUCCESS",

}
//permission types
export const PermissionActionType={
	PERMISSION_ROUTE_LIST:"PERMISSION_ROUTE_LIST",
	PERMISSION_PAGINATION:"PERMISSION_PAGINATION",
	
	PERMISSION_CREATED_SUCCESS:"PERMISSION_CREATED_SUCCESS",
	PERMISSION_EDIT_SUCCESS:"PERMISSION_EDIT_SUCCESS",
	PERMISSION_UPDATE_SUCCESS:"PERMISSION_UPDATE_SUCCESS",
	PERMISSION_DELETED_SUCCESS:"PERMISSION_DELETED_SUCCESS",
}

// role action
export const RoleActionType={
	ROLE_PAGINATION:"ROLE_PAGINATION",
	ROLE_CREATED_SUCCESS:"ROLE_CREATED_SUCCESS",
	ROLE_EDIT_SUCCESS:"ROLE_EDIT_SUCCESS",
	ROLE_UPDATED_SUCCESS:"ROLE_UPDATED_SUCCESS",
	ROLE_DELETED_SUCCESS:"DELETED_SUCCESS",
}

//user action type
export const UserActionType = {
	USER_PAGINATION: "SET_USERS",
	USER_CREATED_SUCCESS: "USER_CREATED_SUCCESS",
	USER_EDIT_SUCCESS: "USER_EDIT_SUCCESS",
	USER_UPDATED_SUCCESS: "USER_UPDATED_SUCCESS",
	USER_DELETED_SUCCESS: "USER_DELETED_SUCCESS",
}