//notification types
export const  NotificationActionType = {
	MESSAGE_OBJ :"MESSAGE_OBJ"
};

// auth types
export const AuthActionType = {
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	LOGIN_FAILED:"LOGIN_FAILED",
	LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
	LOGOUT_FAILED:'LOGOUT_FAILED',
	SET_USER_PERMISSION:'SET_USER_PERMISSION',
}

//log types
export const LogActionType ={
	SET_LOG:'SET_LOG'
}

//message types
export const MessageActionType={
	SET_USER_MESSAGE : "SET_USER_MESSAGE",
	MESSAGE_CREATED_SUCCESS:"MESSAGE_CREATED_SUCCESS"
}
//permission types
export const PermissionActionType={
	SET_ROUTELIST:"SET_ROUTELIST",
	SET_PERMISSIONS:"SET_PERMISSIONS",
	SET_PERMISSION:"SET_PERMISSION",
	PERMISSION_CREATED_SUCCESS:"PERMISSION_CREATED_SUCCESS",
	PERMISSION_EDIT_SUCCESS:"PERMISSION_EDIT_SUCCESS",
	PERMISSION_UPDATE_SUCCESS:"PERMISSION_UPDATE_SUCCESS",
	PERMISSION_DELETED_SUCCESS:"PERMISSION_DELETED_SUCCESS",
}

// role action
export const RoleActionType={
	SET_ROLES:"SET_ROLES",
	SET_ROLE:"SET_ROLE",
	ROLE_CREATED_SUCCESS:"ROLE_CREATED_SUCCESS",
	ROLE_EDIT_SUCCESS:"ROLE_EDIT_SUCCESS",
	ROLE_UPDATED_SUCCESS:"ROLE_UPDATED_SUCCESS",
	ROLE_DELETED_SUCCESS:"DELETED_SUCCESS",
}

//user action type
export const UserActionType = {
	SET_USERS: "SET_USERS",
	SET_USER: "SET_USER",
	SET_CHAT_USERS:"SET_CHAT_USERS",
	USER_CREATED_SUCCESS: "USER_CREATED_SUCCESS",
	USER_EDIT_SUCCESS: "USER_EDIT_SUCCESS",
	USER_UPDATED_SUCCESS: "USER_UPDATED_SUCCESS",
	USER_DELETED_SUCCESS: "USER_DELETED_SUCCESS",
}